repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        stages: [manual]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [manual]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: "^((src|backend)/|tests/)"
        stages: [manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        stages: [manual]
      - id: trailing-whitespace
        stages: [manual]
      - id: check-yaml
        stages: [manual]
      - id: check-merge-conflict
        stages: [manual]
      - id: detect-private-key
        stages: [manual]
      - id: check-added-large-files
        args: ["--maxkb=500"]
        stages: [manual]

  - repo: local
    hooks:
      - id: black-local
        name: black (local)
        entry: black
        language: system
        types: [python]
      - id: isort-local
        name: isort (local)
        entry: isort
        language: system
        types: [python]
      - id: flake8-local
        name: flake8 (local)
        entry: flake8
        language: system
        types: [python]