apiVersion: 1

groups:
  - orgId: 1
    name: Consciousness KPI Alerts
    folder: Liminal
    interval: 1m
    rules:
      - uid: memory-timeline-backlog-high
        title: Memory Timeline Backlog High
        condition: C
        data:
          - refId: A
            queryType: timeSeriesQuery
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              datasource:
                type: prometheus
                uid: PBFA97CFB590B2093
              editorMode: code
              expr: memory_timeline_backlog_size
              instant: false
              intervalMs: 15000
              maxDataPoints: 43200
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              operation: gt
              threshold: 500
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          severity: critical
        labels:
          service: consciousness

      - uid: ml-pipeline-success-low
        title: ML Pipeline Success Ratio Low
        condition: C
        data:
          - refId: A
            queryType: timeSeriesQuery
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              datasource:
                type: prometheus
                uid: PBFA97CFB590B2093
              editorMode: code
              expr: sum(rate(ml_pipeline_runs_total{status="success"}[15m])) / clamp_min(sum(rate(ml_pipeline_runs_total[15m])), 0.0001)
              instant: false
              intervalMs: 15000
              maxDataPoints: 43200
          - refId: B
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              operation: lt
              threshold: 0.8
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 10m
        annotations:
          severity: warning
        labels:
          service: consciousness

      - uid: neo4j-saturation-high
        title: Neo4j Saturation High
        condition: C
        data:
          - refId: A
            queryType: timeSeriesQuery
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              datasource:
                type: prometheus
                uid: PBFA97CFB590B2093
              editorMode: code
              expr: neo4j_saturation_ratio
              instant: false
              intervalMs: 15000
              maxDataPoints: 43200
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              operation: gt
              threshold: 0.85
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 3m
        annotations:
          severity: critical
        labels:
          service: consciousness
