version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=secure_password
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
    networks:
      - security-net

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.0
    hostname: wazuh-indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ELASTIC_CLUSTER_NAME=wazuh-cluster"
      - "ELASTIC_NODE_NAME=wazuh-indexer"
      - "ELASTIC_NETWORK_HOST=0.0.0.0"
      - "ELASTIC_DISCOVERY_TYPE=single-node"
      - "ELASTIC_BOOTSTRAP_MEMORY_LOCK=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/usr/share/elasticsearch/data
    networks:
      - security-net

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    hostname: wazuh-dashboard
    restart: always
    ports:
      - "443:443"
    environment:
      - ELASTICSEARCH_URL=https://wazuh-indexer:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=secure_password
      - WAZUH_API_URL=https://wazuh-manager:55000
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr3tP4ssw0rd
    networks:
      - security-net
    depends_on:
      - wazuh-indexer
      - wazuh-manager

networks:
  security-net:
    driver: bridge

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  wazuh-indexer-data:
