# Список сервисов для системы "Лёгкие"
# Формат: имя: url
# HTTP(S) endpoints проверяются через GET
# tcp://host:port проверяются через сокет
# Можно добавить/убрать сервисы по своему усмотрению

log_viewer: http://127.0.0.1:5000/health
redis: tcp://127.0.0.1:6379
prometheus: http://127.0.0.1:9090/-/healthy
