receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

extensions:
  health_check:
  pprof:
  zpages:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: liminal
  
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
