resolver: lts-21.12

packages:
  - .

extra-deps:
  - aeson-2.0.4.0
  - wai-3.4.2
  - warp-3.3.19
  - text-2.0.3
  - attoparsec-0.14.5
  - servant-0.20
  - servant-server-0.20
  - servant-client-0.20
  - servant-docs-0.20
  - servant-swagger-0.20
  - swagger2-2.3.4
  - vector-0.13.1.0
  - transformers-0.6.1
  - mtl-2.3.1
  - text-icu-0.7.0.2
  - regex-tdfa-1.3.3
  - parsec-3.20.1.1
  - lens-5.2.1
  - neo4j-haskell-driver-1.0.0
  - redis-0.16.0
